##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## makefile
##

DIRECTORY	=	lib/my/

NAME	=	make

all:	$(NAME)

$(NAME):
	make --directory=$(DIRECTORY)
	make clean --directory=$(DIRECTORY)
