##
## EPITECH PROJECT, 2021
## Groundhog
## File description:
## Makefile
##

SRC		= 	groundhog.py \

NAME	=	groundhog

all: $(NAME)

$(NAME):
		cp groundhog.py groundhog
		chmod 777 $(NAME)

clean:
		rm -f $(NAME)

fclean:	clean

re:	fclean all
